### ISSUE TITLE
"slash.on is not a function"

### ISSUE THREAD

**Issue by SlenkyDev** [shadeoxide/slash-activities#1]
Hi there, 
I'm trying to use this as the base for my bot activities, however when I try to use it, edited or not, I get an error claiming that the "slash.on" function doesn't exist.
![error](https://user-images.githubusercontent.com/71548884/115113323-0e59c700-9f8a-11eb-8c21-97c141fe8434.png)
I have all of the modules installed and the bot works if I remove the slash command stuff. 
I also have it in the correct order.

Once again, I get this error even if I try to use the stock bot, hope you can help/fix the issue,
Thanks.

**Comment by Taryro55** [comment]
Hey, same issue here. Could you link a version of the code without the slash commands until the author fixes it?

**Comment by sohamsuvarna** [comment]
If I am not wrong, you are using the version of discord-slash-commands from npm, you need to install it from GitHub which can be done by `npm i https://github.com/ShadeDevelopment/slash-activities`, hope this helps you :)

**Comment by SlenkyDev** [comment]
Thanks!
