### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by arararat** [shadeoxide/slash-activities#2]
I hosted it my self but when the bot is online in discord server ...... When I try to use Slash command I can't see the bot having any slash command please help

**Comment by sujalgoel** [comment]
check whether the bot has the perms of creating slash commands. Make sure to invite your bot with `application.commands` perms.

**Comment by sohamsuvarna** [comment]
is your issue fixed?

**Comment by sohamsuvarna** [comment]
closing this for now, let me know if the issue still exists
